@startuml

skinparam {
   dpi 200
}

title Message Style - Sequence Diagram

participant "User"
participant "Developer" as Dev
participant "GitLab" as GL
participant "App Service" as AS


Dev -> GL  : Push to master
GL -> AS   : GitLab /notifies/ App\nService about new code
AS -> GL   : App Service fetches\nnew code from GitLab
AS -> AS   : Build App
AS -> AS   : Run App
User -> AS : Use application


@enduml
